# Generated by Django 5.0.6 on 2024-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_discount',
            field=models.IntegerField(default=0),
        ),
    ]
