# Generated by Django 5.0.6 on 2024-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_discount',
            field=models.IntegerField(default=1),
        ),
    ]
