# Generated by Django 5.0.6 on 2024-06-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
