# Generated by Django 5.0.6 on 2024-06-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_addtocart_total_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addtocart',
            table='AddTocart',
        ),
    ]
