# Generated by Django 5.0.6 on 2024-06-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_addtocart_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='quantitiy',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
        migrations.AddField(
            model_name='addtocart',
            name='items',
            field=models.ManyToManyField(to='products.cartitem'),
        ),
    ]
