# Generated by Django 5.0.6 on 2024-06-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_order_products_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
